### ISSUE TITLE
Unexpected behavior when making GET request at "/servers/:id/kills" endpoint

### ISSUE THREAD

**Issue by porthog** [Harrison-Miller/kagstats#10] opened 2020-03-12 23:35 UTC
From what I can tell in the api.go file, this route should be supported and handled by a "getServerKills" function. However, when I attempt a GET request at the endpoint, I get an error:

> error getting kills: Error 1054: Unknown column 'player.statsBan' in 'where clause'

In an attempt to get around this, I've tried using the endpoint "/kills/" with a query parameter of "?server={serverId}", but this returns any result whose serverId value begins with the given {serverId}.

**Comment by Harrison-Miller** [comment] 2020-03-13 00:05
ah the problem is the query references player instead of killer.

**Comment by Harrison-Miller** [comment] 2020-03-13 00:30
closing issue fixed and live: https://kagstats.com/api/servers/1/kills

**Closed by Harrison-Miller** 2020-03-13 00:30 UTC
